# Generated by Django 4.2.7 on 2024-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200)),
                ('favicon', models.ImageField(upload_to='site_settings/')),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.CharField(max_length=255)),
                ('background_video', models.FileField(blank=True, null=True, upload_to='site_settings/')),
            ],
        ),
    ]
