# Generated by Django 4.2.7 on 2024-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_site_description_sitesettings_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='support_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
