# Generated by Django 4.2.7 on 2024-07-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_authpage_bgimg_sitesettings_site_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='live_chat_wgt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='open_hrs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
