# Generated by Django 4.2.7 on 2024-07-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_address_sitesettings_live_chat_wgt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_btn',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
