# Generated by Django 4.2.7 on 2024-07-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_payment_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='proof_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='proofs_of_payment/'),
        ),
    ]
